<?php

namespace Database\Seeders;

use App\Models\UserBaganList;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class dataMember extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        UserBaganList::insert(
            [
                ['nama' => 'Dede Faisal Ramadan', 'nik' => '150745', 'team' => 'DST'],
                ['nama' => 'Agung Sutrisno', 'nik' => '150848', 'team' => 'Assembling'],
                ['nama' => 'Muhammad Irhamni', 'nik' => '150849', 'team' => 'Assembling'],
                ['nama' => 'Supriyanto', 'nik' => '150856', 'team' => 'DST'],
                ['nama' => 'Wahyu Firmansyah', 'nik' => '150857', 'team' => 'Painting'],
                ['nama' => 'Deni Iswanto', 'nik' => '150858', 'team' => 'DST'],
                ['nama' => 'Agus Setiawan', 'nik' => '151068', 'team' => 'DST'],
                ['nama' => 'Muhammad Didik Mustakim', 'nik' => '151069', 'team' => 'Assembling'],
                ['nama' => 'Muchammad Chakiki', 'nik' => '151070', 'team' => 'Assembling'],
                ['nama' => 'Mochamad Bisri Mustofa', 'nik' => '151071', 'team' => 'Assembling'],
                ['nama' => 'M. Bima Fani Anggara', 'nik' => '151072', 'team' => 'Assembling'],
                ['nama' => 'Rosidin', 'nik' => '151073', 'team' => 'Assembling'],
                ['nama' => 'Arif Wicaksono', 'nik' => '151075', 'team' => 'Assembling'],
                ['nama' => 'Hendryk Rahmawan', 'nik' => '151177', 'team' => 'Assembling'],
                ['nama' => 'M. Amin Mada Arie Baya', 'nik' => '151179', 'team' => 'Assembling'],
                ['nama' => 'Ahmat Samsul Arifin', 'nik' => '151180', 'team' => 'Assembling'],
                ['nama' => 'Ahmad Sairozi', 'nik' => '151182', 'team' => 'Assembling'],
                ['nama' => 'Zainul Arifin', 'nik' => '151183', 'team' => 'Assembling'],
                ['nama' => 'Achmad Zakariyah', 'nik' => '151288', 'team' => 'Painting'],
                ['nama' => 'Ali Hidayat', 'nik' => '151289', 'team' => 'Painting'],
                ['nama' => 'Apriyanto', 'nik' => '151290', 'team' => 'Assembling'],
                ['nama' => 'Muhammad Aminudin', 'nik' => '151292', 'team' => 'Assembling'],
                ['nama' => 'Rizal Ardiansyah', 'nik' => '151293', 'team' => 'Painting'],
                ['nama' => 'Chandra Surya Lesmana', 'nik' => '160205', 'team' => 'DST'],
                ['nama' => 'Elda Sasmita', 'nik' => '160206', 'team' => 'Assembling'],
                ['nama' => 'Roni Puji Purwanto', 'nik' => '160311', 'team' => 'Assembling'],
                ['nama' => 'Irham Rahmadhani', 'nik' => '160313', 'team' => 'Assembling'],
                ['nama' => 'M Khisom', 'nik' => '160316', 'team' => 'DST'],
                ['nama' => 'Mukhammad Mas\'udi', 'nik' => '160318', 'team' => 'Assembling'],
                ['nama' => 'Muchamad Yanto', 'nik' => '160423', 'team' => 'Assembling'],
                ['nama' => 'Imam Hanafi', 'nik' => '160526', 'team' => 'Assembling'],
                ['nama' => 'Mohammad Cholid', 'nik' => '160531', 'team' => 'DST'],
                ['nama' => 'Agung Santoso', 'nik' => '160533', 'team' => 'Assembling'],
                ['nama' => 'Albertus Ifan Setiawan', 'nik' => '161041', 'team' => 'Assembling'],
                ['nama' => 'Irwansyah Aprilliyanto', 'nik' => '161042', 'team' => 'DST'],
                ['nama' => 'Wildan Egga Pratama', 'nik' => '170413', 'team' => 'Assembling'],
                ['nama' => 'Yulio Angga Andika Putra', 'nik' => '171029', 'team' => 'Assembling'],
                ['nama' => 'Feri Fajar Ferdiansyah', 'nik' => '171133', 'team' => 'Painting'],
                ['nama' => 'Mokhamad Sakroni', 'nik' => '180104', 'team' => 'Painting'],
                ['nama' => 'Khoirul Ikbal', 'nik' => '180113', 'team' => 'Painting'],
                ['nama' => 'Achmad Nur Cahyo', 'nik' => '180114', 'team' => 'Assembling'],
                ['nama' => 'Hendro Prasetyo', 'nik' => '180234', 'team' => 'Assembling'],
                ['nama' => 'Mochammad Syaifudin', 'nik' => '180245', 'team' => 'Assembling'],
                ['nama' => 'Nur Cholis', 'nik' => '190836', 'team' => 'DST'],
                ['nama' => 'M. Taufiq Hidayat', 'nik' => '200315', 'team' => 'Assembling'],
                ['nama' => 'Mokhamad Dwi Mustofa', 'nik' => '200934', 'team' => 'Assembling'],
                ['nama' => 'Mochammad Ulil Abshor', 'nik' => '200940', 'team' => 'Painting'],
                ['nama' => 'Mokhammad Andi Khoirudin', 'nik' => '200942', 'team' => 'Assembling'],
                ['nama' => 'Ahmad Habib As Sahab', 'nik' => '200943', 'team' => 'Assembling'],
                ['nama' => 'Delvi Hafiludin', 'nik' => '201161', 'team' => 'Assembling'],
                ['nama' => 'Mukhammad Roudon', 'nik' => '201163', 'team' => 'DST'],
                ['nama' => 'Krisna Adi Purnama', 'nik' => '201164', 'team' => 'Painting'],
                ['nama' => 'Nasoikhul Firdaus', 'nik' => '201171', 'team' => 'Assembling'],
                ['nama' => 'Dedy Haryanto', 'nik' => '210751', 'team' => 'Assembling'],
                ['nama' => 'Fiqri', 'nik' => '210753', 'team' => 'Assembling'],
                ['nama' => 'Anfa Dhio Frihandipa', 'nik' => '211082', 'team' => 'Assembling'],
                ['nama' => 'Muhammad Yusril', 'nik' => '211192', 'team' => 'Painting'],
                ['nama' => 'M. Syahrul Syaifani', 'nik' => '220327', 'team' => 'Assembling'],
                ['nama' => 'Bahroni Syafrizal', 'nik' => '220340', 'team' => 'Assembling'],
                ['nama' => 'Mochammad Zainur Roziqin', 'nik' => '220993', 'team' => 'Painting'],
                ['nama' => 'Chalvin Yudha Ayiyin', 'nik' => '221202', 'team' => 'Painting'],
                ['nama' => 'Mukhammad Arif Pratama', 'nik' => '230111', 'team' => 'Painting'],
                ['nama' => 'Jumiati', 'nik' => '230119', 'team' => 'DST'],
                ['nama' => 'Ainun Qolby Sulistiyo Putri', 'nik' => '230505', 'team' => 'Assembling'],
                ['nama' => 'Eka Nadya Fatmawati', 'nik' => '230507', 'team' => 'Assembling'],
                ['nama' => 'Mohammad Riszki Alan Pratama', 'nik' => '230801', 'team' => 'Painting'],
                ['nama' => 'Muhammad Nasihudin', 'nik' => '231101', 'team' => 'Painting'],
                ['nama' => 'Achmad Riadin', 'nik' => '231102', 'team' => 'Painting'],
                ['nama' => 'Angga Bagus Maulana', 'nik' => '240106', 'team' => 'Painting'],
                ['nama' => 'Tamhid Masaji', 'nik' => '240201', 'team' => 'Assembling'],
                ['nama' => 'Hari Setiawan', 'nik' => '240206', 'team' => 'Painting'],
                ['nama' => 'M. Nadif', 'nik' => '240207', 'team' => 'Assembling'],
                ['nama' => 'Nur Amin', 'nik' => '240208', 'team' => 'Assembling'],
                ['nama' => 'Alfin Mahendra', 'nik' => '240301', 'team' => 'Assembling'],
                ['nama' => 'Wisnu Adi Rinenggo', 'nik' => '240303', 'team' => 'Painting'],
                ['nama' => 'Moh Sulkhan Ashari', 'nik' => '240304', 'team' => 'Painting'],
                ['nama' => 'Nurhasan', 'nik' => '240401', 'team' => 'Assembling'],
                ['nama' => 'Yusuf Pratama', 'nik' => '240402', 'team' => 'Assembling'],
                ['nama' => 'Mochammad Djati Kemal', 'nik' => '240403', 'team' => 'Assembling'],
                ['nama' => 'Moch. Haikal Lutfi', 'nik' => '240406', 'team' => 'Painting'],
                ['nama' => 'Laksana Syair Achmadi', 'nik' => '240409', 'team' => 'Painting'],
                ['nama' => 'Susilowati', 'nik' => '240415', 'team' => 'Assembling'],
                ['nama' => 'Indah Afiati', 'nik' => '250101', 'team' => 'DST'],
                ['nama' => 'Fatimatuz Zahro', 'nik' => '250102', 'team' => 'Assembling'],
                ['nama' => 'Dinda Lukita Sari', 'nik' => '250106', 'team' => 'Assembling'],
                ['nama' => 'A. Taufiqurrohman', 'nik' => '250202', 'team' => 'Assembling'],
                ['nama' => 'Mohammad Mi\'raj Akbar', 'nik' => '250203', 'team' => 'Painting'],
                ['nama' => 'Achmad Nur Huda', 'nik' => '250301', 'team' => 'DST'],
                ['nama' => 'M. Pandu Gautama Wiranagara', 'nik' => '250302', 'team' => 'DST'],
                ['nama' => 'Nisa Aulia', 'nik' => '250401', 'team' => 'DST'],
                ['nama' => 'Ratna Sari Dewi', 'nik' => '250705', 'team' => 'DST'],
                ['nama' => 'Mukhamad Junaedi', 'nik' => '250901', 'team' => 'Assembling'],
                ['nama' => 'Siti Hafifatul Chasanah', 'nik' => '251001', 'team' => 'Assembling'],
                ['nama' => 'Harris Hermawan', 'nik' => '251002', 'team' => 'Assembling'],
                ['nama' => 'Moch. Novan Dwi Yudianto', 'nik' => '251003', 'team' => 'Assembling'],
                ['nama' => 'Moch Ansor', 'nik' => '251004', 'team' => 'Painting'],
                ['nama' => 'Mukhammad Hasim Asyari', 'nik' => '251005', 'team' => 'Assembling'],
                ['nama' => 'Ari Firmansyah', 'nik' => '251006', 'team' => 'Assembling'],
                ['nama' => 'Dian Novianti Pratiwi', 'nik' => '251007', 'team' => 'Assembling'],
                ['nama' => 'Muhammad Fatkhul Jinan', 'nik' => '251008', 'team' => 'Assembling'],
                ['nama' => 'Yusuf Novrianto', 'nik' => '251009', 'team' => 'Assembling'],
                ['nama' => 'Sela Safira', 'nik' => '251010', 'team' => 'Assembling'],
                ['nama' => 'Anita Syarifatuddiniyah', 'nik' => '251011', 'team' => 'Assembling'],
                ['nama' => 'Diva Safitri', 'nik' => '251012', 'team' => 'Assembling'],
                ['nama' => 'Nur Hasanah Dwi Yulianti', 'nik' => '251013', 'team' => 'Assembling'],
                ['nama' => 'Aziza Prawita Dewanti', 'nik' => '251014', 'team' => 'Assembling'],
                ['nama' => 'Maya Nur Ayu Fitriani', 'nik' => '251015', 'team' => 'Assembling'],
                ['nama' => 'Manda Dwi Novitasari', 'nik' => '251016', 'team' => 'Assembling'],
                ['nama' => 'Muhammad Agus Arif Setiyo Budi', 'nik' => '251017', 'team' => 'DST'],
            ]
    );
    }
}
